### ISSUE TITLE
Encrypted password and 403 Forbidden error

### ISSUE THREAD

**Issue by Kirri777** [Michsior14/docker-mods#10]
1. If you have an encrypted password stored in the "PASS" variable within a Docker environment, you can't establishing a connection to the Transmission rpc.
2. To avoid a 403 Forbidden error, it's crucial to include the IP address "127.0.0.1" in the rpc-whitelist variable within the settings.json file.

**Comment by Michsior14** [comment]
1. There is nothing special happening in the mod regarding auth handling. By the encryption you mean docker secrets or something else? If something else, is it supported by the container without the mod?
2. Since this is a mod to main image, the address should be added via `WHITELIST`. It's also only needed if the variable is used in the first place. I guess here we just need more documentation in the repo.
